version: '3'
networks: 
    default:
        external: 
            name: contained
services: 
    postgres:
        image: postgres:14
        container_name: postgres
        restart: unless-stopped
        tty: true
        environment:
            POSTGRES_USER: 
            POSTGRES_PASSWORD: 
            PGDATA: /var/lib/postgresql/data/pgdata
            TZ: Asia/Shanghai
        expose: 
            - 5432
        volumes: 
            - /home/database/postgres:/var/lib/postgresql/data
        networks: 
            default:
                ipv4_address: 192.168.170.8
