version: '3'
services: 
    nginx:
        image: axizdkr/tengine
        container_name: nginx
        restart: always
        volumes: 
            - /home/config/nginx:/etc/nginx
            - /home/AutoCert/data/acme:/home/AutoCert/data/acme
            - /home/log/nginx:/var/log/nginx
        network_mode: host