version: '3'
networks: 
    default:
        external: 
            name: contained
services: 
    mysql:
        image: mariadb:latest
        container_name: mysql
        command: 
            - --default_authentication_plugin=mysql_native_password
        restart: always
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: PASSWORD
            MYSQL_DATABASE: app
            MYSQL_USER: app
            MYSQL_PASSWORD: PASSWORD
        expose: 
            - 3306
        volumes: 
            - /home/database/mysql:/var/lib/mysql
            - /home/log/mysql:/var/log/mysql
        networks: 
            default:
                ipv4_address: 192.168.170.3
