version: '3'
networks: 
    default:
        external: 
            name: contained
services: 
    mongo:
        image: mongo:latest
        container_name: mongo
        command: --auth --unixSocketPrefix /dev/shm --filePermissions 0777
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: PASSWORD
        expose: 
            - 27017
        volumes: 
            - /home/database/mongo/configdb:/data/configdb
            - /home/database/mongo/db:/data/db
            - /home/log/mongo:/var/log/mongodb
        networks: 
            default:
                ipv4_address: 192.168.170.4